backend:
  name: git-gateway
  branch: main

site_url: https://makeventures.netlify.app

publish_mode: editorial_workflow

media_folder: 'src/assets/'

collections:
  - name: 'projects'
    label: 'Projects'
    folder: 'src/content/projects'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Navigation title', name: 'navTitle', widget: 'string' }
      - { label: 'Status', name: 'status', widget: 'string' }
      - { label: 'Completed date', name: 'completedDate', widget: 'datetime' }
      - { label: 'Hero image', name: 'heroImage', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
